title: Joseph Christopher
logo: /annotate-with-joe/assets/img/joseph-christopher.png
description: A portfolio of my data annotation and AI training work.
show_downloads: false
theme: jekyll-theme-minimal
