title: Annotate with Joe
logo: /annotate-with-joe/assets/img/joseph-christopher.jpg
description: AI Data Annotation Portfolio | Video Annotation • Action Segmentation • Data Quality
show_downloads: false
theme: jekyll-theme-minimal
